/**
 * AUTO-GENERATED by scripts/generate-audio.mjs
 * Azure OpenAI TTS audio + Whisper word-accurate caption timings.
 * Re-run the script after changing narration text.
 */

export interface CaptionEntry {
  start: number;
  end: number;
  text: string;
}

export interface SceneNarration {
  text: string;
  captions: CaptionEntry[];
}

const title: SceneNarration = {
  text: "Meet ContextWeaver. The Microsoft Copilot agent giving your entire codebase institutional memory.",
  captions: [
    { start: 0, end: 120, text: "Meet ContextWeaver the Microsoft CoPilot agent giving your" },
    { start: 113, end: 188, text: "entire codebase institutional memory" },
  ],
};

const hackIdea: SceneNarration = {
  text: "Copilot knows your syntax — but not your team's intent. ContextWeaver fuses Git, ADO, and Teams into one queryable knowledge graph. Grounded answers in seconds.",
  captions: [
    { start: 0, end: 94, text: "Copilot knows your syntax but not your team's" },
    { start: 87, end: 206, text: "intent ContextWeaver fuses Git ADO and Teams into" },
    { start: 199, end: 306, text: "one queryable knowledge graph Grounded answers in seconds" },
  ],
};

const architecture: SceneNarration = {
  text: "Four layers working in concert. Azure Functions capture every commit, ticket, and meeting. Cosmos DB and Azure AI Search store the knowledge graph. GPT-4o and Semantic Kernel orchestrate reasoning, surfaced natively through Copilot Chat.",
  captions: [
    { start: 0, end: 111, text: "Four layers working in concert Azure Functions capture" },
    { start: 104, end: 222, text: "every commit ticket and meeting Cosmos DB and" },
    { start: 215, end: 322, text: "Azure AI Search store the knowledge graph GPT" },
    { start: 315, end: 422, text: "4 0 and Semantic Kernel orchestrate reasoning surface" },
    { start: 415, end: 470, text: "natively through Copilot Chat" },
  ],
};

const codeWalkthrough: SceneNarration = {
  text: "The action handler runs hybrid retrieval — combining vector search with graph traversal. GPT-4o generates a grounded, cited answer. The ingestion pipeline extracts intent from every pull request and writes causal relationships into the graph.",
  captions: [
    { start: 0, end: 108, text: "The Action Handler runs hybrid retrieval combining vector" },
    { start: 101, end: 220, text: "search with graph traversal GPT 4 0 generates" },
    { start: 213, end: 353, text: "a grounded cited answer The Ingestion Pipeline extracts" },
    { start: 346, end: 429, text: "intent from every pull request and writes causal" },
    { start: 422, end: 478, text: "relationships into the graph" },
  ],
};

const benefits: SceneNarration = {
  text: "Four wins: institutional memory that outlasts team turnover, ten-times faster onboarding, cross-signal correlation no other tool offers, and zero UI tax — it all lives inside Copilot Chat.",
  captions: [
    { start: 0, end: 109, text: "Four wins institutional memory that outlasts team turnover" },
    { start: 123, end: 225, text: "10 times faster onboarding cross signal correlation no" },
    { start: 218, end: 319, text: "other tool offers and zero UI tax It" },
    { start: 312, end: 370, text: "all lives inside Copilot Chat" },
  ],
};

const futureScope: SceneNarration = {
  text: "Next: proactive context push, architecture drift detection, multi-repo federation, and a Copilot Studio connector for every team. The journey has just begun.",
  captions: [
    { start: 0, end: 134, text: "Next proactive context push architecture drift detection multi" },
    { start: 127, end: 208, text: "repo federation and a co pilot studio connector" },
    { start: 201, end: 289, text: "for every team The journey has just begun" },
  ],
};

export const NARRATION = {
  title,
  hackIdea,
  architecture,
  codeWalkthrough,
  benefits,
  futureScope,
} as const;
